apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: legare123-api
spec:
  template:
    spec:
      containers:
        - image: gcr.io/cloudrun/hello
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: production
            - name: DATABASE_URL
              value: sqlite:///./legare.db
            - name: JWT_SECRET
              value: change-me-in-production
